# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vegimshala/CLionProjects/unary-prototype-csv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vegimshala/CLionProjects/unary-prototype-csv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vegimshala/CLionProjects/unary-prototype-csv/CMakeFiles /Users/vegimshala/CLionProjects/unary-prototype-csv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vegimshala/CLionProjects/unary-prototype-csv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named unary_prototype_csv

# Build rule for target.
unary_prototype_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unary_prototype_csv
.PHONY : unary_prototype_csv

# fast build rule for target.
unary_prototype_csv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/build
.PHONY : unary_prototype_csv/fast

#=============================================================================
# Target rules for targets named binary_creator

# Build rule for target.
binary_creator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 binary_creator
.PHONY : binary_creator

# fast build rule for target.
binary_creator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/build
.PHONY : binary_creator/fast

src/aggregators/avg_aggregator.o: src/aggregators/avg_aggregator.cpp.o
.PHONY : src/aggregators/avg_aggregator.o

# target to build an object file
src/aggregators/avg_aggregator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/avg_aggregator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/avg_aggregator.cpp.o
.PHONY : src/aggregators/avg_aggregator.cpp.o

src/aggregators/avg_aggregator.i: src/aggregators/avg_aggregator.cpp.i
.PHONY : src/aggregators/avg_aggregator.i

# target to preprocess a source file
src/aggregators/avg_aggregator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/avg_aggregator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/avg_aggregator.cpp.i
.PHONY : src/aggregators/avg_aggregator.cpp.i

src/aggregators/avg_aggregator.s: src/aggregators/avg_aggregator.cpp.s
.PHONY : src/aggregators/avg_aggregator.s

# target to generate assembly for a file
src/aggregators/avg_aggregator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/avg_aggregator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/avg_aggregator.cpp.s
.PHONY : src/aggregators/avg_aggregator.cpp.s

src/aggregators/count_aggregator.o: src/aggregators/count_aggregator.cpp.o
.PHONY : src/aggregators/count_aggregator.o

# target to build an object file
src/aggregators/count_aggregator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/count_aggregator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/count_aggregator.cpp.o
.PHONY : src/aggregators/count_aggregator.cpp.o

src/aggregators/count_aggregator.i: src/aggregators/count_aggregator.cpp.i
.PHONY : src/aggregators/count_aggregator.i

# target to preprocess a source file
src/aggregators/count_aggregator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/count_aggregator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/count_aggregator.cpp.i
.PHONY : src/aggregators/count_aggregator.cpp.i

src/aggregators/count_aggregator.s: src/aggregators/count_aggregator.cpp.s
.PHONY : src/aggregators/count_aggregator.s

# target to generate assembly for a file
src/aggregators/count_aggregator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/count_aggregator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/count_aggregator.cpp.s
.PHONY : src/aggregators/count_aggregator.cpp.s

src/aggregators/max_aggregator.o: src/aggregators/max_aggregator.cpp.o
.PHONY : src/aggregators/max_aggregator.o

# target to build an object file
src/aggregators/max_aggregator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/max_aggregator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/max_aggregator.cpp.o
.PHONY : src/aggregators/max_aggregator.cpp.o

src/aggregators/max_aggregator.i: src/aggregators/max_aggregator.cpp.i
.PHONY : src/aggregators/max_aggregator.i

# target to preprocess a source file
src/aggregators/max_aggregator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/max_aggregator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/max_aggregator.cpp.i
.PHONY : src/aggregators/max_aggregator.cpp.i

src/aggregators/max_aggregator.s: src/aggregators/max_aggregator.cpp.s
.PHONY : src/aggregators/max_aggregator.s

# target to generate assembly for a file
src/aggregators/max_aggregator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/max_aggregator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/max_aggregator.cpp.s
.PHONY : src/aggregators/max_aggregator.cpp.s

src/aggregators/min_aggregator.o: src/aggregators/min_aggregator.cpp.o
.PHONY : src/aggregators/min_aggregator.o

# target to build an object file
src/aggregators/min_aggregator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/min_aggregator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/min_aggregator.cpp.o
.PHONY : src/aggregators/min_aggregator.cpp.o

src/aggregators/min_aggregator.i: src/aggregators/min_aggregator.cpp.i
.PHONY : src/aggregators/min_aggregator.i

# target to preprocess a source file
src/aggregators/min_aggregator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/min_aggregator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/min_aggregator.cpp.i
.PHONY : src/aggregators/min_aggregator.cpp.i

src/aggregators/min_aggregator.s: src/aggregators/min_aggregator.cpp.s
.PHONY : src/aggregators/min_aggregator.s

# target to generate assembly for a file
src/aggregators/min_aggregator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/min_aggregator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/min_aggregator.cpp.s
.PHONY : src/aggregators/min_aggregator.cpp.s

src/aggregators/sum_aggregator.o: src/aggregators/sum_aggregator.cpp.o
.PHONY : src/aggregators/sum_aggregator.o

# target to build an object file
src/aggregators/sum_aggregator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/sum_aggregator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/sum_aggregator.cpp.o
.PHONY : src/aggregators/sum_aggregator.cpp.o

src/aggregators/sum_aggregator.i: src/aggregators/sum_aggregator.cpp.i
.PHONY : src/aggregators/sum_aggregator.i

# target to preprocess a source file
src/aggregators/sum_aggregator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/sum_aggregator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/sum_aggregator.cpp.i
.PHONY : src/aggregators/sum_aggregator.cpp.i

src/aggregators/sum_aggregator.s: src/aggregators/sum_aggregator.cpp.s
.PHONY : src/aggregators/sum_aggregator.s

# target to generate assembly for a file
src/aggregators/sum_aggregator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/aggregators/sum_aggregator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/aggregators/sum_aggregator.cpp.s
.PHONY : src/aggregators/sum_aggregator.cpp.s

src/binary_creator.o: src/binary_creator.cpp.o
.PHONY : src/binary_creator.o

# target to build an object file
src/binary_creator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/binary_creator.cpp.o
.PHONY : src/binary_creator.cpp.o

src/binary_creator.i: src/binary_creator.cpp.i
.PHONY : src/binary_creator.i

# target to preprocess a source file
src/binary_creator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/binary_creator.cpp.i
.PHONY : src/binary_creator.cpp.i

src/binary_creator.s: src/binary_creator.cpp.s
.PHONY : src/binary_creator.s

# target to generate assembly for a file
src/binary_creator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/binary_creator.cpp.s
.PHONY : src/binary_creator.cpp.s

src/data_io.o: src/data_io.cpp.o
.PHONY : src/data_io.o

# target to build an object file
src/data_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/data_io.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/data_io.cpp.o
.PHONY : src/data_io.cpp.o

src/data_io.i: src/data_io.cpp.i
.PHONY : src/data_io.i

# target to preprocess a source file
src/data_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/data_io.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/data_io.cpp.i
.PHONY : src/data_io.cpp.i

src/data_io.s: src/data_io.cpp.s
.PHONY : src/data_io.s

# target to generate assembly for a file
src/data_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/data_io.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/binary_creator.dir/build.make CMakeFiles/binary_creator.dir/src/data_io.cpp.s
.PHONY : src/data_io.cpp.s

src/data_processing.o: src/data_processing.cpp.o
.PHONY : src/data_processing.o

# target to build an object file
src/data_processing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/data_processing.cpp.o
.PHONY : src/data_processing.cpp.o

src/data_processing.i: src/data_processing.cpp.i
.PHONY : src/data_processing.i

# target to preprocess a source file
src/data_processing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/data_processing.cpp.i
.PHONY : src/data_processing.cpp.i

src/data_processing.s: src/data_processing.cpp.s
.PHONY : src/data_processing.s

# target to generate assembly for a file
src/data_processing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unary_prototype_csv.dir/build.make CMakeFiles/unary_prototype_csv.dir/src/data_processing.cpp.s
.PHONY : src/data_processing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... binary_creator"
	@echo "... unary_prototype_csv"
	@echo "... src/aggregators/avg_aggregator.o"
	@echo "... src/aggregators/avg_aggregator.i"
	@echo "... src/aggregators/avg_aggregator.s"
	@echo "... src/aggregators/count_aggregator.o"
	@echo "... src/aggregators/count_aggregator.i"
	@echo "... src/aggregators/count_aggregator.s"
	@echo "... src/aggregators/max_aggregator.o"
	@echo "... src/aggregators/max_aggregator.i"
	@echo "... src/aggregators/max_aggregator.s"
	@echo "... src/aggregators/min_aggregator.o"
	@echo "... src/aggregators/min_aggregator.i"
	@echo "... src/aggregators/min_aggregator.s"
	@echo "... src/aggregators/sum_aggregator.o"
	@echo "... src/aggregators/sum_aggregator.i"
	@echo "... src/aggregators/sum_aggregator.s"
	@echo "... src/binary_creator.o"
	@echo "... src/binary_creator.i"
	@echo "... src/binary_creator.s"
	@echo "... src/data_io.o"
	@echo "... src/data_io.i"
	@echo "... src/data_io.s"
	@echo "... src/data_processing.o"
	@echo "... src/data_processing.i"
	@echo "... src/data_processing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

